/* XCL bootstrap compiler: parser with nested block depth. */
#include <stdio.h>
#include <string.h>
#include <ctype.h>
typedef struct { char name[64]; int argc; } Fn;
static Fn fns[256]; static int fn_count;
static char *trim(char *s){while(isspace((unsigned char)*s))s++;char*e=s+strlen(s);while(e>s&&isspace((unsigned char)e[-1]))--e;*e=0;return s;}
static int fnhead(const char*l,char*n,size_t z,int*a){if(strncmp(l,"fn ",3))return 0;const char*p=l+3;while(*p&&isspace((unsigned char)*p))p++;size_t k=0;while(p[k]&&p[k]!='('&&!isspace((unsigned char)p[k]))k++;if(!k||k>=z)return 0;memcpy(n,p,k);n[k]=0;p+=k;while(*p&&isspace((unsigned char)*p))p++;if(*p!='(')return 0;p++;const char*e=strchr(p,')');if(!e)return 0;size_t q=(size_t)(e-p);while(q&&isspace((unsigned char)p[q-1]))q--;*a=q?1:0;return 1;}
static void collect(const char*l){char n[64];int a;if(fnhead(l,n,sizeof(n),&a)&&fn_count<256){strncpy(fns[fn_count].name,n,63);fns[fn_count].name[63]=0;fns[fn_count].argc=a;fn_count++;}}
static void strlit(FILE*o,const char*p,const char*e){fputc('"',o);for(;p<e;p++){if(*p=='"')fputs("\\\"",o);else if(*p=='\\'&&p+1<e){fputc('\\',o);fputc(p[1],o);p++;}else if(*p=='\n')fputs("\\n",o);else fputc(*p,o);}fputc('"',o);}
static int cond(FILE*o,const char*s,const char*kw,size_t n){if(strncmp(s,kw,n))return 0;char*q=strchr((char*)s,'"'),*e=q?strrchr(q+1,'"'):0;if(!q||!e)return -1;fprintf(o,"%s (xcl_streq(cmd, ",kw);strlit(o,q+1,e);fputs(")) {\n",o);return 1;}
static int compile(FILE*o,const char*path){FILE*i=fopen(path,"r");if(!i)return 0;char b[4096];int in=0,d=0;while(fgets(b,sizeof(b),i)){char*s=trim(b);if(!*s||*s=='#')continue;if(!in&&strncmp(s,"fn ",3)==0){char n[64];int a;if(!fnhead(s,n,sizeof(n),&a)){fclose(i);return 0;}fprintf(o,"void %s(%s) {\n",n,a?"const char *cmd":"void");in=1;d=1;continue;}if(!in){fprintf(stderr,"xclc: statement outside function in %s: %s\n",path,s);fclose(i);return 0;}if(!strncmp(s,"} else if cmd == ",18)){char*q=strchr(s,'"'),*e=q?strrchr(q+1,'"'):0;if(d<=1||!q||!e){fclose(i);return 0;}d--;fputs("} else if (xcl_streq(cmd, ",o);strlit(o,q+1,e);fputs(")) {\n",o);d++;continue;}if(!strncmp(s,"} else {",8)){if(d<=1){fclose(i);return 0;}fputs("} else {\n",o);continue;}if(!strncmp(s,"if cmd == ",10)){if(cond(o,s,"if",2)<0){fclose(i);return 0;}d++;continue;}if(!strncmp(s,"else if cmd == ",15)){if(cond(o,s,"else if",7)<0){fclose(i);return 0;}d++;continue;}if(!strcmp(s,"else {")){fputs("else {\n",o);d++;continue;}if(!strcmp(s,"}")){d--;fputs("}\n",o);if(d==0)in=0;else if(d<0){fclose(i);return 0;}continue;}if(!strncmp(s,"print ",6)){char*q=strchr(s+6,'"'),*e=q?strrchr(q+1,'"'):0;if(!q||!e){fclose(i);return 0;}fputs("terminal_write(",o);strlit(o,q+1,e);fputs(");\n",o);continue;}if(!strcmp(s,"clear;")){fputs("terminal_clear();\n",o);continue;}if(!strcmp(s,"backspace;")){fputs("terminal_backspace();\n",o);continue;}if(!strcmp(s,"return;")){fputs("return;\n",o);continue;}if(!strncmp(s,"call ",5)){char n[64];if(sscanf(s,"call %63[^;];",n)==1){fprintf(o,"%s();\n",trim(n));continue;}}fprintf(stderr,"xclc: unsupported XCL statement in %s: %s\n",path,s);fclose(i);return 0;}if(in||d){fclose(i);return 0;}fclose(i);return 1;}
int main(int ac,char**av){if(ac<3)return 2;const char*outp=av[ac-1];for(int j=1;j<ac-1;j++){FILE*i=fopen(av[j],"r");if(!i)return 1;char l[4096];while(fgets(l,sizeof(l),i)){char*s=trim(l);if(!strncmp(s,"fn ",3))collect(s);}fclose(i);}FILE*o=fopen(outp,"w");if(!o)return 1;fputs("#include \"terminal.h\"\n#include \"xcl_runtime.h\"\n\n",o);for(int j=0;j<fn_count;j++)fprintf(o,"void %s(%s);\n",fns[j].name,fns[j].argc?"const char *cmd":"void");for(int j=1;j<ac-1;j++)if(!compile(o,av[j])){fclose(o);remove(outp);return 1;}fclose(o);return 0;}
